-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mar. 10 mai 2022 à 06:07
-- Version du serveur : 8.0.27
-- Version de PHP : 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `moviestreaming`
--

-- --------------------------------------------------------

--
-- Structure de la table `movielist`
--

DROP TABLE IF EXISTS `movielist`;
CREATE TABLE IF NOT EXISTS `movielist` (
  `idMovie` int NOT NULL AUTO_INCREMENT,
  `nameMovie` varchar(255) NOT NULL,
  `descriptionMovie` varchar(1500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `authorMovie` varchar(255) NOT NULL,
  `yearMovie` varchar(255) NOT NULL,
  `durationMovie` varchar(255) NOT NULL,
  `pathMovie` varchar(255) NOT NULL,
  `pathImage` varchar(255) NOT NULL,
  PRIMARY KEY (`idMovie`)
) ENGINE=MyISAM AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `movielist`
--

INSERT INTO `movielist` (`idMovie`, `nameMovie`, `descriptionMovie`, `authorMovie`, `yearMovie`, `durationMovie`, `pathMovie`, `pathImage`) VALUES
(18, 'Back to the future', 'Back to the Future is a 1985 American science fiction film directed by Robert Zemeckis, and written by Zemeckis and Bob Gale. It stars Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, and Thomas F. Wilson. Set in 1985, the story follows Marty McFly (Fox), a teenager accidentally sent back to 1955 in a time-traveling DeLorean automobile built by his eccentric scientist friend Doctor Emmett \"Doc\" Brown (Lloyd). Trapped in the past, Marty inadvertently prevents his future parents\' meeting—threatening his existence—and is forced to reconcile the pair and somehow get back to the future.', 'Robert Zemeckis', '1985', '1h56', 'video/Back To The Future (1985) Theatrical Trailer - Michael J. Fox Movie HD.mp4', 'image/backtothefuture.png'),
(17, 'Grease', 'Grease is a 1978 American musical romantic comedy film based on the 1971 musical of the same name by Jim Jacobs and Warren Casey. Written by Bronte Woodard[2] (adaptation by Allan Carr) and directed by Randal Kleiser in his theatrical feature film debut, the film depicts the lives of greaser Danny Zuko and Australian transfer student Sandy Olsson, who develop an attraction for each other during a summer romance. The film stars John Travolta and Olivia Newton-John as Danny and Sandy.', 'Randal Kleiser', '1978', '1h50', 'video/GREASE _ Trailer _ Paramount Movies.mp4', 'image/grease_reissueok.jpg'),
(19, 'Dirty Dancing', 'Dirty Dancing is a 1987 American romantic drama dance film written by Eleanor Bergstein, produced by Linda Gottlieb, and directed by Emile Ardolino. Starring Patrick Swayze and Jennifer Grey, it tells the story of Frances &quot;Baby&quot; Houseman (Grey), a young woman who falls in love with dance instructor Johnny Castle (Swayze) at a vacation resort.', 'Emile Ardolino', '1987', '1h40', 'video/Dirty Dancing (1987) Official Trailer  - Patrick Swayze, Jennifer Grey Movie HD.mp4', 'image/dirtydancing.png'),
(20, 'Home alone', 'Home Alone is a 1990 American comedy film directed by Chris Columbus and written and produced by John Hughes. It is the first film in the Home Alone franchise, and stars Macaulay Culkin, Joe Pesci, Daniel Stern, John Heard, and Catherine O&#039;Hara. Culkin plays Kevin McCallister, a boy who defends his suburban Chicago home from burglars after his family accidentally leaves him behind on their Christmas vacation to Paris.', 'Chris Columbus', '1990', '1h43', 'video/Homealone.mp4', 'image/home alone.png'),
(21, 'Love Actually', 'Love Actually is a 2003 Christmas-themed romantic comedy-drama film written and directed by Richard Curtis. It features an ensemble cast, composed predominantly of British actors, many of whom had worked with Curtis in previous film and television projects. Mostly filmed on location in London, the screenplay delves into different aspects of love as shown through ten separate stories involving a wide variety of individuals, many of whom are shown to be interlinked as the tales progress. The story begins five weeks before Christmas and is played out in a weekly countdown until the holiday, followed by an epilogue that takes place one month later.', 'Richard Curtis', '2003', '2h16', 'video/loveactually.mp4', 'image/loveactually.png'),
(22, 'Indiana Jones: Raiders of the Lost Ark', 'Raiders of the Lost Ark[a] is a 1981 American action-adventure film directed by Steven Spielberg, with a screenplay by Lawrence Kasdan, based on a story by George Lucas and Philip Kaufman. It stars Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey, John Rhys-Davies, and Denholm Elliott. Ford portrays Indiana Jones, a globe-trotting archaeologist vying with Nazi German forces in 1936 to recover the long-lost Ark of the Covenant, a relic said to make an army invincible. Teaming up with his tough former lover Marion Ravenwood (Allen), Jones races to stop rival archaeologist Dr. René Belloq (Freeman) from guiding the Nazis to the Ark and its power.', 'Steven Spielberg', '1981', '1h55', 'video/raiders.mp4', 'image/raiders.png'),
(23, 'Titanic', 'Titanic is a 1997 American epic romance and disaster film directed, written, produced, and co-edited by James Cameron. Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of the RMS Titanic, and stars Leonardo DiCaprio and Kate Winslet as members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage. Also starring are Billy Zane, Kathy Bates, Frances Fisher, Gloria Stuart, Bernard Hill, Jonathan Hyde, Victor Garber, and Bill Paxton.', 'James Cameron', '1997', '2h16', 'video/titanic.mp4', 'image/titanic.png'),
(24, 'Jurassic Park', 'Jurassic Park is a 1993 American science fiction action film[3] directed by Steven Spielberg and produced by Kathleen Kennedy and Gerald R. Molen. It is the first installment in the Jurassic Park franchise, and the first film in the Jurassic Park original trilogy, and is based on the 1990 novel of the same name by Michael Crichton and a screenplay written by Crichton and David Koepp. The film is set on the fictional island of Isla Nublar, located off Central America&#039;s Pacific Coast near Costa Rica. There, wealthy businessman John Hammond and a team of genetic scientists have created a wildlife park of de-extinct dinosaurs. When industrial sabotage leads to a catastrophic shutdown of the park&#039;s power facilities and security precautions, a small group of visitors and Hammond&#039;s grandchildren struggle to survive and escape the perilous island.', 'Steven Spielberg', '1993', '2h08', 'video/jurassicpark.mp4', 'image/jurassicpark.png'),
(25, 'Mary Poppins', 'Mary Poppins is a 1964 American musical fantasy film directed by Robert Stevenson and produced by Walt Disney, with songs written and composed by the Sherman Brothers. The screenplay is by Bill Walsh and Don DaGradi, based on P. L. Travers&#039;s book series Mary Poppins. The film, which combines live-action and animation, stars Julie Andrews in her feature film debut as Mary Poppins, who visits a dysfunctional family in London and employs her unique brand of lifestyle to improve the family&#039;s dynamic. Dick Van Dyke, David Tomlinson, and Glynis Johns are featured in supporting roles. The film was shot entirely at the Walt Disney Studios in Burbank, California, using painted London background scenes.', 'Robert Stevenson', '1964', '2h19', 'video/marypoppins.mp4', 'image/marypoppins.png'),
(26, 'Toy Story', 'Toy Story is a 1995 American computer-animated comedy film produced by Pixar Animation Studios and released by Walt Disney Pictures. The first installment in the Toy Story franchise, it was the first entirely computer-animated feature film, as well as the first feature film from Pixar. The film was directed by John Lasseter (in his feature directorial debut) and written by Joss Whedon, Andrew Stanton, Joel Cohen, and Alec Sokolow from a story by Lasseter, Stanton, Pete Docter, and Joe Ranft. The film features music by Randy Newman, was produced by Bonnie Arnold and Ralph Guggenheim, and was executive-produced by Steve Jobs and Edwin Catmull. The film features the voices of Tom Hanks, Tim Allen, Don Rickles, Wallace Shawn, John Ratzenberger, Jim Varney, Annie Potts, R. Lee Ermey, John Morris, Laurie Metcalf, and Erik von Detten. Taking place in a world where toys come to life when humans are not present, the plot focuses on the relationship between an old-fashioned pull-string cowboy doll named Woody and a modern astronaut action figure, Buzz Lightyear, as they evolve from rivals competing for the affections of their owner, Andy Davis, to friends who work together to be reunited with Andy after being separated from him.', 'John Lasseter', '1995', '1h21', 'video/toystory.mp4', 'image/toystory.png'),
(27, 'The Shawshank Redemption', 'The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. It tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis &quot;Red&quot; Redding (Morgan Freeman), and becomes instrumental in a money-laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.', 'Frank Darabont', '1994', '2h22', 'video/evades.mp4', 'image/shawshank.png'),
(28, 'Bridget Jone&#039;s Diary', 'Bridget Jones&#039;s Diary is a 2001 romantic comedy film directed by Sharon Maguire and written by Richard Curtis, Andrew Davies, and Helen Fielding. A co-production of the United Kingdom, United States and France, it is based on Fielding&#039;s 1996 novel of the same name, which is a reinterpretation of Jane Austen&#039;s 1813 novel Pride and Prejudice. The adaptation stars Renée Zellweger as Bridget Jones, a 32-year-old British single woman, who writes a diary which focuses on the things she wishes to happen in her life. However, her life changes when two men vie for her affection, portrayed by Colin Firth and Hugh Grant. Jim Broadbent and Gemma Jones appear in supporting roles. Production began in August 2000 and ended in November 2000, and took place largely on location in London and the home counties.', 'Sharon Maguire', '2001', '1h36', 'video/1434659607842-pgv4ql-1564460751861.mp4', 'image/bridget.png'),
(29, 'Harry Potter and the Philosopher&#039;s Stone', 'Harry Potter and the Philosopher&#039;s Stone (released in the United States, India and the Philippines as Harry Potter and the Sorcerer&#039;s Stone) is a 2001 fantasy film directed by Chris Columbus and distributed by Warner Bros. Pictures, based on J. K. Rowling&#039;s 1997 novel of the same name. Produced by David Heyman and screenplay by Steve Kloves, it is the first instalment of the Harry Potter film series. The film stars Daniel Radcliffe as Harry Potter, with Rupert Grint as Ron Weasley, and Emma Watson as Hermione Granger. Its story follows Harry&#039;s first year at Hogwarts School of Witchcraft and Wizardry as he discovers that he is a famous wizard and begins his formal wizarding education.', 'Chris Columbus', '2001', '2h32', 'video/harrypotter.mp4', 'image/harrypotter.png'),
(30, 'The Wizard of Oz', 'The Wizard of Oz is a 1939 American musical fantasy film produced by Metro-Goldwyn-Mayer. An adaptation of L. Frank Baum&#039;s 1900 children&#039;s fantasy novel The Wonderful Wizard of Oz, the film was primarily directed by Victor Fleming (who left the production to take over the troubled Gone with the Wind), and stars Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr, Jack Haley, Billie Burke and Margaret Hamilton. Noel Langley, Florence Ryerson, and Edgar Allan Woolf received credit for the screenplay, but others made uncredited contributions. The songs were written by Edgar &quot;Yip&quot; Harburg and composed by Harold Arlen. The musical score and incidental music were composed by Herbert Stothart.', 'Victor Fleming', '1939', '1h41', 'video/1434659607842-pgv4ql-1564209095791.mp4', 'image/800px-Wizard_of_oz_movie_poster.jpg'),
(31, 'Forrest Gump', 'Forrest Gump is a 1994 American comedy-drama film directed by Robert Zemeckis and written by Eric Roth. It is based on the 1986 novel of the same name by Winston Groom and stars Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson and Sally Field. The story depicts several decades in the life of Forrest Gump (Hanks), a slow-witted and kindhearted man from Alabama who witnesses and unwittingly influences several defining historical events in the 20th century United States. The film differs substantially from the novel.', 'Robert Zemeckis', '1994', '2h22', 'video/Forrest Gump - Trailer (1).mp4', 'image/forrestgump.png'),
(32, 'Die Hard', 'Die Hard is a 1988 American action film directed by John McTiernan, with a screenplay by Jeb Stuart and Steven E. de Souza. It is based on the 1979 novel Nothing Lasts Forever by Roderick Thorp, and it stars Bruce Willis, Alan Rickman, Alexander Godunov, and Bonnie Bedelia. Die Hard follows New York City police detective John McClane (Willis) who is caught up in a terrorist takeover of a Los Angeles skyscraper while visiting his estranged wife. Reginald VelJohnson, William Atherton, Paul Gleason, and Hart Bochner feature in supporting roles.', 'John McTiernan', '1988', '2h12', 'video/diehard.mp4', 'image/diehard.png'),
(33, 'E.T the Extra-Terrestrial', 'E.T. the Extra-Terrestrial (or simply E.T.) is a 1982 American science fiction film produced and directed by Steven Spielberg and written by Melissa Mathison. It tells the story of Elliott, a boy who befriends an extraterrestrial dubbed E.T., who is left behind on Earth. Along with his friends and family, Elliott must find a way to help E.T. return home while avoiding the government. The film stars Dee Wallace, Henry Thomas, Peter Coyote, Robert MacNaughton and Drew Barrymore.', 'Steven Spielberg', '1982', '2h00', 'video/ET The Extra Terrestrial (1982) Official 20th Anniversary Trailer Movie HD.mp4', 'image/ET.png'),
(34, 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Pirates of the Caribbean: The Curse of the Black Pearl is a 2003 American fantasy swashbuckler film directed by Gore Verbinski and the first film in the Pirates of the Caribbean film series. Produced by Walt Disney Pictures and Jerry Bruckheimer, the film is based on Walt Disney&#039;s Pirates of the Caribbean attraction at Disney theme parks.[3] The story follows pirate Jack Sparrow (Johnny Depp) and blacksmith Will Turner (Orlando Bloom) as they rescue the kidnapped Elizabeth Swann (Keira Knightley) from the cursed crew of the Black Pearl, captained by Hector Barbossa (Geoffrey Rush), who become undead skeletons in moonlight.', 'Gore Verbinski', '2003', '2h23', 'video/Pirates of the Caribbean The Curse of the Black Pearl Trailer #1 - Johnny Depp HD.mp4', 'image/pirates.jpg'),
(35, 'The Goonies', 'The Goonies is a 1985 American adventure comedy film co-produced and directed by Richard Donner from a screenplay by Chris Columbus, based on a story by Steven Spielberg. In the film, kids who live in the &quot;Goon Docks&quot; neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate. During the adventure, they are chased by a family of criminals who want the treasure for themselves.', 'Richard Donner', '1985', '1h54', 'video/goonies.mp4', 'image/goonies.png'),
(36, 'Ghostbusters', 'Ghostbusters is a 1984 American supernatural comedy film directed and produced by Ivan Reitman, and written by Dan Aykroyd and Harold Ramis. It stars Bill Murray, Aykroyd, and Ramis as Peter Venkman, Ray Stantz, and Egon Spengler, three eccentric parapsychologists who start a ghost-catching business in New York City. It also stars Sigourney Weaver and Rick Moranis, and features Annie Potts, William Atherton, and Ernie Hudson in supporting roles.', 'Ivan Reitman', '1984', '1h45', 'video/ghostbusters.mp4', 'image/ghostbusters.png'),
(38, 'The Terminator', 'The Terminator is a 1984 American science fiction action film directed by James Cameron. It stars Arnold Schwarzenegger as the Terminator, a cyborg assassin sent back in time from 2029 to 1984 to kill Sarah Connor (Linda Hamilton), whose unborn son will one day save mankind from extinction by Skynet, a hostile artificial intelligence in a post-apocalyptic future. Kyle Reese (Michael Biehn) is a soldier sent back in time to protect Sarah. The screenplay is credited to Cameron and producer Gale Anne Hurd. Co-writer William Wisher Jr. received a credit for additional dialogue.', 'James Cameron', '1984', '1h47', 'video/terminator.mp4', 'image/termintor.png'),
(37, 'JAWS', 'Jaws is a 1975 American thriller film directed by Steven Spielberg, based on the 1974 novel by Peter Benchley. In the film, a man-eating great white shark attacks beachgoers at a summer resort town, prompting police chief Martin Brody (Roy Scheider) to hunt it with the help of a marine biologist (Richard Dreyfuss) and a professional shark hunter (Robert Shaw). Murray Hamilton plays the mayor, and Lorraine Gary portrays Brody&#039;s wife. The screenplay is credited to Benchley, who wrote the first drafts, and actor-writer Carl Gottlieb, who rewrote the script during principal photography.', 'Steven Spielberg', '1975', '2h04', 'video/Jaws - Theatrical Trailer (HD) (1975).mp4', 'image/JAWS.png'),
(39, 'Top Gun', 'Top Gun is a 1986 American action drama film directed by Tony Scott, and produced by Don Simpson and Jerry Bruckheimer, in association with Paramount Pictures. The screenplay was written by Jim Cash and Jack Epps Jr., and was inspired by an article titled &quot;Top Guns&quot; published in California magazine three years earlier. The film stars Tom Cruise and Kelly McGillis with Val Kilmer, Anthony Edwards and Tom Skerritt in supporting roles. Cruise plays Lieutenant Pete &quot;Maverick&quot; Mitchell, a young naval aviator aboard the aircraft carrier USS Enterprise. He and his Radar Intercept Officer, LTJG Nick &quot;Goose&quot; Bradshaw (Edwards) are given the chance to train at the US Navy&#039;s Fighter Weapons School at Naval Air Station Miramar in San Diego, California.', 'Tony Scott', '1986', '1h50', 'video/topgun.mp4', 'image/topgun.png'),
(40, 'Star Wars: Episode IV – A New Hope', 'Star Wars  is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox. It stars Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, David Prowse, James Earl Jones, Anthony Daniels, Kenny Baker and Peter Mayhew. It is the first film in the Star Wars film series and fourth chronological chapter of the &quot;Skywalker Saga&quot;.', 'George Lucas', '1977', '2h01', 'video/starwars.mp4', 'image/starwars.png'),
(41, 'The Lion King', 'The Lion King is a 1994 American animated musical drama film[4] produced by Walt Disney Feature Animation and released by Walt Disney Pictures. It is the 32nd Disney animated feature film and the fifth animated film produced during a period known as the Disney Renaissance. The Lion King was directed by Roger Allers and Rob Minkoff (in their feature directorial debuts) and produced by Don Hahn, from a screenplay by Irene Mecchi, Jonathan Roberts, and Linda Woolverton. Its original songs were written by composer Elton John and lyricist Tim Rice, with a score by Hans Zimmer. The film features an ensemble voice cast that includes Matthew Broderick, James Earl Jones, Jeremy Irons, Jonathan Taylor Thomas, Moira Kelly, Nathan Lane, Ernie Sabella, Rowan Atkinson, Robert Guillaume, Madge Sinclair (in her last film role), Whoopi Goldberg, Cheech Marin, and Jim Cummings. The story takes place in a kingdom of lions in Africa and was influenced by the Biblical stories of Joseph and Moses, and William Shakespeare&#039;s Hamlet.', 'Roger Allers & Rob Minkoff', '1994', '1h28', 'video/lionking.mp4', 'image/lionking.png'),
(42, 'The Lord of the Rings: The Fellowship of the Ring', 'The Lord of the Rings: The Fellowship of the Ring is a 2001 epic fantasy adventure film directed by Peter Jackson, based on the 1954 novel The Fellowship of the Ring, the first volume of J. R. R. Tolkien&#039;s The Lord of the Rings. The film is the first installment in the Lord of the Rings trilogy. It was produced by Barrie M. Osborne, Jackson, Fran Walsh and Tim Sanders, and written by Walsh, Philippa Boyens and Jackson. The film features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, and Andy Serkis. It was followed in 2002 by The Two Towers and in 2003 by The Return of the King.', 'Peter Jackson', '2001', '2h58', 'video/lordoftherings.mp4', 'image/lordoftherings.png'),
(43, 'Finding Nemo', 'Finding Nemo is a 2003 American computer-animated adventure film produced by Pixar Animation Studios and released by Walt Disney Pictures. Directed by Andrew Stanton with co-direction by Lee Unkrich, the screenplay was written by Stanton, Bob Peterson, and David Reynolds from a story by Stanton. The film stars the voices of Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe, and Geoffrey Rush. It tells the story of an overprotective clownfish named Marlin who, along with a regal blue tang named Dory, searches for his missing son Nemo. Along the way, Marlin learns to take risks and comes to terms with Nemo taking care of himself.', 'Andrew Stanton', '2003', '1h40', 'video/Nemo.mp4', 'image/nemo.png'),
(44, 'Elf', 'Elf is a 2003 American Christmas comedy film directed by Jon Favreau, written by David Berenbaum, and starring Will Ferrell, James Caan, Zooey Deschanel, Mary Steenburgen, Edward Asner, and Bob Newhart. The film centers on Buddy, a human raised by Santa&#039;s elves, who learns about his origins and heads to New York City to meet his biological father.', 'Jon Favreau', '2003', '1h37', 'video/Elf.mp4', 'image/Elf.png'),
(45, 'The Silence of the Lambs', 'The Silence of the Lambs is a 1991 American psychological horror film directed by Jonathan Demme and written by Ted Tally, adapted from Thomas Harris&#039;s 1988 novel. It stars Jodie Foster as Clarice Starling, a young FBI trainee who is hunting a serial killer, &quot;Buffalo Bill&quot; (Ted Levine), who skins his female victims. To catch him, she seeks the advice of the imprisoned Dr. Hannibal Lecter (Anthony Hopkins), a brilliant psychiatrist and cannibalistic serial killer. The film also features performances from Scott Glenn, Anthony Heald and Kasi Lemmons.', 'Jonathan Demme', '1991', '1h58', 'video/Silenceoflamb.mp4', 'image/Silenceoflamb.png'),
(46, 'Alien', 'Alien is a 1979 science fiction horror film directed by Ridley Scott and written by Dan O&#039;Bannon. Based on a story by O&#039;Bannon and Ronald Shusett, it follows the crew of the commercial space tug Nostromo, who encounter the eponymous Alien, an aggressive and deadly extraterrestrial set loose on the ship. The film stars Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, and Yaphet Kotto. It was produced by Gordon Carroll, David Giler, and Walter Hill through their company Brandywine Productions, and was distributed by 20th Century Fox. Giler and Hill revised and made additions to the script; Shusett was executive producer. The Alien and its accompanying artifacts were designed by the Swiss artist H. R. Giger, while concept artists Ron Cobb and Chris Foss designed the more human settings.', 'Ridley Scott', '1979', '1h56', 'video/alien.mp4', 'image/alien.png'),
(47, 'Monsters, Inc.', 'Monsters, Inc. (Monsters, Incorporated) is a 2001 American computer-animated monster comedy film produced by Pixar Animation Studios for Walt Disney Pictures. Featuring the voices of John Goodman, Billy Crystal, Steve Buscemi, James Coburn, Mary Gibbs and Jennifer Tilly, the film was directed by Pete Docter in his directorial debut, and executive produced by John Lasseter and Andrew Stanton. The film centers on two monsters James P. &quot;Sulley&quot; Sullivan and his one-eyed partner and best friend Mike Wazowski who are employed at the titular energy-producing factory Monsters, Inc., which generates power by scaring human children. However, the monster world believes that the children are toxic, and when a little human girl sneaks into the factory, she must be returned home before it&#039;s too late.', 'Pete Docter', '2001', '1h32', 'video/monsters.mp4', 'image/monsters.png'),
(48, 'The Matrix', 'The Matrix is a 1999 science fiction action film written and directed by the Wachowskis. It is the first installment in The Matrix film series, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano. It depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source.When computer programmer Thomas Anderson, under the hacker alias &quot;Neo&quot;, uncovers the truth, he joins a rebellion against the machines along with other people who have been freed from the Matrix.', 'The Wachowskis', '1999', '2h16', 'video/Matrix Trailer HD (1999).mp4', 'image/matrix.png'),
(49, 'It&#039;s a Wonderful Life', 'It&#039;s a Wonderful Life is a 1946 American Christmas fantasy drama film produced and directed by Frank Capra, based on the short story and booklet The Greatest Gift, which Philip Van Doren Stern self-published in 1943 and is in turn loosely based on the 1843 Charles Dickens novella A Christmas Carol. The film stars James Stewart as George Bailey, a man who has given up his personal dreams, in order to help others in his community, and whose thoughts of suicide on Christmas Eve brings about the intervention of his guardian angel, Clarence Odbody (Henry Travers)', 'Frank Capra', '1946', '2h11', 'video/wonderfule.mp4', 'image/wonderfullife.png'),
(50, 'Avatar', 'Avatar (also marketed as James Cameron&#039;s Avatar) is a 2009 American epic science fiction film directed, written, produced, and co-edited by James Cameron and starring Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez, and Sigourney Weaver. The film is set in the mid-22nd century when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the valuable mineral unobtanium. The expansion of the mining colony threatens the continued existence of a local tribe of Na&#039;vi – a humanoid species indigenous to Pandora. The film&#039;s title refers to a genetically engineered Na&#039;vi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora.', 'James Cameron', '2009', '2h42', 'video/avatar.mp4', 'image/avatar.jpg'),
(51, 'Gladiator', 'Gladiator is a 2000 epic historical drama film directed by Ridley Scott and written by David Franzoni, John Logan, and William Nicholson. The film was co-produced and released by DreamWorks Pictures and Universal Pictures. DreamWorks Pictures distributed the film in North America while Universal Pictures released it internationally through United International Pictures. It stars Russell Crowe, Joaquin Phoenix, Connie Nielsen, Ralf Möller, Oliver Reed (in his final role), Djimon Hounsou, Derek Jacobi, John Shrapnel, Richard Harris, and Tommy Flanagan. Crowe portrays Roman general Maximus Decimus Meridius, who is betrayed when Commodus, the ambitious son of Emperor Marcus Aurelius, murders his father and seizes the throne. Reduced to slavery, Maximus becomes a gladiator and rises through the ranks of the arena to avenge the murders of his family and his emperor.', 'Ridley Scott', '2000', '2h35', 'video/Gladiator trailer.mp4', 'image/gladiator.png'),
(52, 'Monty Python&#039;s Life of Brian', 'Monty Python&#039;s Life of Brian, also known as Life of Brian, is a 1979 British comedy film starring and written by the comedy group Monty Python (Graham Chapman, John Cleese, Terry Gilliam, Eric Idle, Terry Jones and Michael Palin). It was directed by Jones. The film tells the story of Brian Cohen (played by Chapman), a young Jewish-Roman man who is born on the same day as—and next door to—Jesus, and is subsequently mistaken for the Messiah.', 'Terry Jones', '1979', '1h34', 'video/lifeofbrian.mp4', 'image/lifeofbrian.png'),
(53, 'Monty Python and the Holy Grail', 'Monty Python and the Holy Grail is a 1975 British comedy film inspired by the Arthurian legend, written and performed by the Monty Python comedy group (Chapman, Cleese, Gilliam, Idle, Jones, and Palin), directed by Gilliam and Jones in their directorial debuts. It was conceived during the hiatus between the third and fourth series of their BBC Television series Monty Python&#039;s Flying Circus.', 'Terry Gilliam, Terry Jones', '1975', '1h32', 'video/Monty Python and the Holy Grail Modern Trailer.mp4', 'image/montypython.png'),
(54, 'The Good, the Bad and the Ugly', 'The Good, the Bad and the Ugly (Italian: Il buono, il brutto, il cattivo, literally &quot;The good, the ugly, the bad&quot;) is a 1966 Italian epic spaghetti Western film directed by Sergio Leone and starring Clint Eastwood as &quot;the Good&quot;, Lee Van Cleef as &quot;the Bad&quot;, and Eli Wallach as &quot;the Ugly&quot;.Its screenplay was written by Age &amp; Scarpelli, Luciano Vincenzoni, and Leone (with additional screenplay material and dialogue provided by an uncredited Sergio Donati), based on a story by Vincenzoni and Leone. Director of photography Tonino Delli Colli was responsible for the film&#039;s sweeping widescreen cinematography, and Ennio Morricone composed the film&#039;s score, including its main theme. It was an Italian-led production with co-producers in Spain, West Germany, and the United States. Most of the filming took place in Spain.', 'Sergio Leone', '1966', '2h57', 'video/The Good, the Bad and the Ugly - Theatrical Trailer Remastered in HD.mp4', 'image/The Good, the Bad and the Ugly - Theatrical Trailer Remastered in HD.png'),
(55, 'Edward Scissorhands', 'Edward Scissorhands is a 1990 American fantasy romance film directed by Tim Burton. It was produced by Burton and Denise Di Novi, and written by Caroline Thompson from a story by her and Burton. Johnny Depp plays an artificial humanoid named Edward, an unfinished creation who has scissor blades instead of hands. The young man is taken in by a suburban family and falls in love with their teenage daughter, Kim (Winona Ryder). Additional roles were played by Dianne Wiest, Anthony Michael Hall, Kathy Baker, Vincent Price, and Alan Arkin.', 'Tim Burton', '1990', '1h45', 'video/Edward scissorhands.mp4', 'image/Edward scissorhands.png'),
(56, 'Groundhog Day', 'Groundhog Day is a 1993 American fantasy comedy film directed by Harold Ramis, with a screenplay by him and Danny Rubin. It stars Bill Murray, Andie MacDowell, and Chris Elliott. Murray portrays Phil Connors, a cynical television weatherman covering the annual Groundhog Day event in Punxsutawney, Pennsylvania, who becomes trapped in a time loop, forcing him to relive February 2nd repeatedly. The film also stars Stephen Tobolowsky, Brian Doyle-Murray, Marita Geraghty, Angela Paton, Rick Ducommun, Rick Overton, and Robin Duke.', 'Harold Ramis', '1993', '1h41', 'video/Groundhog Day (1993) - Trailer HD.mp4', 'image/Groundhog Day (1993) - Trailer HD.png'),
(57, 'The Godfather', 'The Godfather is a 1972 American crime film directed by Francis Ford Coppola, who co-wrote the screenplay with Mario Puzo, based on Puzo&#039;s best-selling 1969 novel of the same name. The film stars Marlon Brando, Al Pacino, James Caan, Richard Castellano, Robert Duvall, Sterling Hayden, John Marley, Richard Conte, and Diane Keaton. It is the first installment in The Godfather trilogy. The story, spanning from 1945 to 1955, chronicles the Corleone family under patriarch Vito Corleone (Brando), focusing on the transformation of his youngest son, Michael Corleone (Pacino), from reluctant family outsider to ruthless mafia boss.', 'Francis Ford Coppola', '1972', '2h55', 'video/Thegodfather.mp4', 'image/The Godfather.png'),
(58, 'Pulp Fiction', 'Pulp Fiction is a 1994 American black comedy crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary. Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.', 'Quentin Tarantino', '1994', '2h34', 'video/pulpfiction.mp4', 'image/pulpfiction.png'),
(59, 'Rocky', 'Rocky is a 1976 American sports drama film directed by John G. Avildsen and written by and starring Sylvester Stallone. It is the first installment in the Rocky franchise. It also stars Talia Shire, Burt Young, Carl Weathers, and Burgess Meredith. In the film, Rocky Balboa (Stallone), an uneducated, small-time club fighter and debt collector gets an unlikely shot at the world heavyweight championship held by Apollo Creed (Weathers).', 'John G. Avildsen', '1976', '1h59', 'video/Rocky (1976) - Trailer (HD).mp4', 'image/rocky.png'),
(60, 'The Dark Knight', 'The Dark Knight is a 2008 superhero film directed, co-produced, and co-written by Christopher Nolan. Based on the DC Comics character Batman, the film is the second installment of Nolan&#039;s The Dark Knight Trilogy and a sequel to 2005&#039;s Batman Begins, starring Christian Bale and supported by Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, and Morgan Freeman. In the film, Bruce Wayne / Batman (Bale), Police Lieutenant James Gordon (Oldman) and District Attorney Harvey Dent (Eckhart) form an alliance to dismantle organized crime in Gotham City, but are menaced by an anarchistic mastermind known as the Joker (Ledger), who seeks to undermine Batman&#039;s influence and throw the city into chaos.', 'Christopher Nolan', '2008', '2h32', 'video/The Dark Knight (2008) Official Trailer #1 - Christopher Nolan Movie HD.mp4', 'image/The Dark Knight.png'),
(61, 'Singin&#039; in the Rain', 'Singin&#039; in the Rain is a 1952 American musical romantic comedy film directed and choreographed by Gene Kelly and Stanley Donen, starring Kelly, Donald O&#039;Connor, and Debbie Reynolds and featuring Jean Hagen, Millard Mitchell and Cyd Charisse. It offers a lighthearted depiction of Hollywood in the late 1920s, with the three stars portraying performers caught up in the transition from silent films to &quot;talkies&quot;.', 'Gene Kelly', '1952', '1h43', 'video/SinginInTheRain.mp4', 'image/SinginInTheRain.png'),
(62, 'Casablanca', 'Casablanca is a 1942 American romantic drama film directed by Michael Curtiz, and starring Humphrey Bogart, Ingrid Bergman, and Paul Henreid. Filmed and set during World War II, it focuses on an American expatriate (Bogart) who must choose between his love for a woman (Bergman) or helping her and her husband (Henreid), a Czech resistance leader, escape from the Vichy-controlled city of Casablanca to continue his fight against the Germans. The screenplay is based on Everybody Comes to Rick&#039;s, an unproduced stage play by Murray Burnett and Joan Alison. The supporting cast features Claude Rains, Conrad Veidt, Sydney Greenstreet, Peter Lorre, and Dooley Wilson.', 'Michael Curtiz', '1942', '1h42', 'video/casablanca.mp4', 'image/casablanca.png'),
(63, 'Mean Girls', 'Mean Girls is a 2004 American teen comedy film directed by Mark Waters and written by Tina Fey. The film stars Lindsay Lohan, Rachel McAdams, Lacey Chabert, Amanda Seyfried, Tim Meadows, Ana Gasteyer, Amy Poehler, and Fey. It is based in part on Rosalind Wiseman&#039;s 2002 non-fiction self-help book, Queen Bees and Wannabes, which describes female high school social cliques, school bullying, and the damaging effects they can have on students. Fey also drew from her own experience at Upper Darby High School as an inspiration for some of the concepts in the film. The plot centers on a naïve teenage girl navigating her way through the social hierarchy of a modern American high school after years of her parents homeschooling her while conducting research in Africa.', 'Mark Waters', '2004', '1h37', 'video/MeansGirls.mp4', 'image/MeansGirls.png'),
(64, 'Psycho', 'Psycho is a 1960 American psychological horror thriller film produced and directed by Alfred Hitchcock and written by Joseph Stefano. It is a film adaptation of the 1959 novel of the same name by Robert Bloch. The film stars Anthony Perkins, Janet Leigh, Vera Miles, John Gavin and Martin Balsam. The plot centers on an encounter between on-the-run embezzler Marion Crane (Leigh) and shy motel proprietor Norman Bates (Perkins) and its aftermath, in which a private investigator (Balsam), Marion&#039;s lover Sam Loomis (Gavin), and her sister Lila (Miles) investigate the cause of her disappearance.', 'Alfred Hitchcock', '1960', '1h49', 'video/Psycho.mp4', 'image/Psycho.png'),
(65, 'Romeo And Juliet', 'Romeo and Juliet (Italian: Romeo e Giulietta) is a 1968 period romantic tragedy film based on the play of the same name by William Shakespeare. Directed and co-written by Franco Zeffirelli, the film stars Leonard Whiting as Romeo and Olivia Hussey as Juliet. Laurence Olivier spoke the film&#039;s prologue and epilogue and dubs the voice of the actor Antonio Pierfederici, who played Lord Montague, but was not credited on-screen. The cast also stars Milo O&#039;Shea, Michael York, John McEnery, Bruce Robinson, and Robert Stephens.', 'Franco Zeffirelli', '1968', '2h18', 'video/RomerAndJuliet.mp4', 'image/RomerAndJuliet.png'),
(66, 'Romeo + Juliet', 'William Shakespeare&#039;s Romeo and Juliet (often shortened to Romeo + Juliet) is a 1996 romantic crime tragedy film directed, co-produced, and co-written by Baz Luhrmann. It is a modernized adaptation of William Shakespeare&#039;s tragedy Romeo and Juliet. The film stars Leonardo DiCaprio and Claire Danes in the title roles of two teenagers who fall in love, despite their being members of feuding families. Brian Dennehy, John Leguizamo, Harold Perrineau, Pete Postlethwaite, Paul Sorvino and Diane Venora also star in supporting roles. It is the third major film version of the play, following a 1936 film and a 1968 film.', 'Baz Luhrmann', '1996', '2h00', 'video/Romeo and Juliet 1996 trailer.mp4', 'image/Romeo and Juliet 1996.png');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
